import { useState, type CSSProperties } from "react";
import { ArrowRight, ArrowUpRight, Check, Clock3, Cloud, Code2, Database, Headphones, Mail, MapPin, Phone, Quote, ShieldCheck, Sparkles, Terminal } from "lucide-react";
import { Link } from "wouter";
import { contactInfo, industries, services } from "@/data/site";

function PageIntro({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: { label: string; href: string } }) {
  return <section className="page-intro"><div className="container article-head animate-in"><span className="eyebrow">{eyebrow}</span><h1 className="display-sm" style={{ margin: "22px 0 24px" }}>{title}</h1><p className="lede">{text}</p>{action && <Link href={action.href} className="button button-primary" style={{ marginTop: 28 }} data-testid="link-intro-action">{action.label} <ArrowUpRight size={15} /></Link>}</div></section>;
}

function SectionLabel({ children }: { children: string }) { return <span className="eyebrow">{children}</span>; }

function CTASection({ title = "Bring us the hard part." }: { title?: string }) {
  return <section className="section-tight" style={{ background: "hsl(var(--primary))", color: "hsl(var(--primary-foreground))" }}><div className="container" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 30, flexWrap: "wrap" }}><div><span className="eyebrow" style={{ color: "inherit" }}>The next useful move</span><h2 style={{ fontSize: "clamp(2.1rem, 5vw, 4.8rem)", lineHeight: .94, letterSpacing: "-.07em", margin: "17px 0 0", maxWidth: 700 }}>{title}</h2></div><Link href="/contact" className="button button-dark" data-testid="link-cta-contact">Let's talk <ArrowRight size={16} /></Link></div></section>;
}

export function HomePage() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="animate-in"><span className="eyebrow">Independent technology partner</span><h1 className="display">Make your next <em>move</em> the right one.</h1><p className="lede">CodeByte helps growing organizations turn complex technology into a clear advantage — from first product idea to the systems that keep the lights on.</p><div className="hero-actions"><Link href="/contact" className="button button-primary" data-testid="link-hero-contact">Talk to CodeByte <ArrowUpRight size={16} /></Link><Link href="/services" className="button button-ghost" style={{ color: "hsl(var(--secondary-foreground))", borderColor: "hsl(210 40% 98% / .3)" }} data-testid="link-hero-services">Explore capabilities <ArrowRight size={16} /></Link></div></div><div className="hero-aside animate-in" style={{ animationDelay: ".15s" }}><div className="orbit"><span className="orbit-dot" /></div><div className="hero-metric"><span className="mono" style={{ color: "hsl(var(--primary))", fontSize: 11 }}>OPERATING PRINCIPLE</span><div className="metric">Clarity<br />before code.</div><p>The best technical answer is the one your team can own, operate, and explain.</p></div></div></div></section>
    <div className="ticker"><div className="ticker-inner"><span>Software delivery</span><span>•</span><span>Cloud operations</span><span>•</span><span>Security that ships</span><span>•</span><span>Human support</span><span>•</span><span>Software delivery</span><span>•</span><span>Cloud operations</span><span>•</span><span>Security that ships</span><span>•</span><span>Human support</span></div></div>
    <div className="container"><div className="proof-strip"><div className="proof"><b>14+</b><span>Years making systems useful</span></div><div className="proof"><b>24/7</b><span>Operational thinking</span></div><div className="proof"><b>5</b><span>Integrated capabilities</span></div><div className="proof"><b>1:1</b><span>Senior-level partnership</span></div></div></div>
    <section className="section"><div className="container"><div className="section-head"><div><SectionLabel>What we do</SectionLabel><h2>Technology with a job to do.</h2></div><Link href="/services" className="text-link" data-testid="link-home-all-services">View all services <ArrowRight size={16} /></Link></div><div className="service-grid">{services.map((service, index) => <Link className="service-card" href={service.path} key={service.path} data-testid={`card-service-${index}`}><div><span className="mono card-icon">{service.code} /</span><h3>{service.title}</h3><p>{service.description}</p></div><ArrowUpRight size={18} /></Link>)}</div></div></section>
    <section className="section case-section"><div className="container case-grid"><div className="case-visual"><div className="bar-chart">{[35, 50, 43, 72, 66, 94, 82].map((height) => <i key={height} style={{ "--height": `${height}%` } as CSSProperties} />)}</div></div><div className="case-copy"><SectionLabel>Proof in practice</SectionLabel><h2>Less firefighting. More forward.</h2><p>A regional care network came to us with disconnected workflows, rising support tickets, and no clear owner for the critical path. We mapped the system, rebuilt the handoffs, and gave their team a platform that could grow with them.</p><Link href="/contact" className="button button-light" data-testid="link-home-case-study">Start with the map <ArrowRight size={15} /></Link><div className="quote"><Quote size={18} color="hsl(var(--primary))" /><br />“CodeByte brought the rare combination of technical depth and calm, direct communication our team needed.”<b>— Operations lead, regional care network</b></div></div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><SectionLabel>Field notes</SectionLabel><h2>Useful thinking for the road ahead.</h2></div><Link href="/insights" className="text-link" data-testid="link-home-insights">Read all insights <ArrowRight size={16} /></Link></div><div className="insight-grid"><Link href="/insights/cloud-readiness" className="insight-card" data-testid="card-insight-cloud"><span className="insight-meta">01 / Cloud operations</span><h3>Cloud readiness is a business conversation.</h3><p>Before you choose a platform, choose what “ready” needs to mean for your people.</p><span className="text-link" style={{ marginTop: 25 }}>Read the note <ArrowRight size={14} /></span></Link><Link href="/insights/secure-by-design" className="insight-card" data-testid="card-insight-secure"><span className="insight-meta">02 / Security</span><h3>Secure by design, not by surprise.</h3><p>Five ways to move security upstream without slowing the work down.</p><span className="text-link" style={{ marginTop: 25 }}>Read the note <ArrowRight size={14} /></span></Link><div className="insight-card"><span className="insight-meta">03 / Perspective</span><h3>Good systems leave room for good work.</h3><p>A short point of view on humane operations and the teams behind the tools.</p><Link href="/contact" className="text-link" style={{ marginTop: 25 }} data-testid="link-home-point-of-view">Talk it through <ArrowRight size={14} /></Link></div></div></div></section>
    <CTASection />
  </>;
}

export function AboutPage() {
  return <><PageIntro eyebrow="About CodeByte" title="A technology partner with a point of view." text="We are a senior-led team for organizations that have outgrown patchwork technology — but do not want to lose the human context behind it." action={{ label: "Meet us in a conversation", href: "/contact" }} /><section className="section"><div className="container split"><div><SectionLabel>Our story</SectionLabel><h2>Big enough for the hard work. Close enough to care.</h2></div><div className="rich-copy"><p>CodeByte began with a simple observation: growing organizations rarely need more technology. They need better decisions about the technology they already have, and a partner who will stay close enough to make those decisions real.</p><p>Today, our work spans product engineering, cloud operations, cybersecurity, managed IT, and applied data. The disciplines are different. The approach is the same: understand the work, name the tradeoffs, and build what lasts.</p><p>We are deliberately practical. No theatre. No black boxes. Just thoughtful people, direct language, and systems that earn their place.</p></div></div></section><section className="section" style={{ background: "hsl(var(--muted))" }}><div className="container"><div className="section-head"><div><SectionLabel>How we work</SectionLabel><h2>Trust is an operating system.</h2></div></div><div className="principles"><div className="principle"><span className="principle-no">01</span><div><h3>Say the useful thing.</h3><p>We make the complicated legible, including the parts that are uncomfortable or inconvenient.</p></div></div><div className="principle"><span className="principle-no">02</span><div><h3>Stay close to the work.</h3><p>Senior people stay involved from first sketch to handover. Your context does not get lost in a process.</p></div></div><div className="principle"><span className="principle-no">03</span><div><h3>Leave the team stronger.</h3><p>Every engagement should increase your confidence, not your dependence on us.</p></div></div></div></div></section><CTASection title="Good partnerships make ambitious work feel possible." /></>;
}

export function ServicesPage() {
  return <><PageIntro eyebrow="Capabilities" title="The right mix of thinking and doing." text="Five connected practices, brought together around the outcomes your organization actually needs." /><section className="section"><div className="container"><div className="service-grid">{services.map((service, index) => <Link className="service-card" href={service.path} key={service.path} data-testid={`service-overview-${index}`}><div><span className="mono card-icon">{service.code} /</span><h3>{service.title}</h3><p>{service.description}</p></div><span className="text-link">See capability <ArrowRight size={15} /></span></Link>)}</div></div></section><section className="section" style={{ background: "hsl(var(--muted))" }}><div className="container split"><div><SectionLabel>One partner, less translation</SectionLabel><h2>Connected decisions beat isolated projects.</h2></div><div className="rich-copy"><p>A new product has infrastructure implications. A security decision affects user experience. A data project changes how teams work. Our practices collaborate from the start, so you do not have to coordinate five different vendors to solve one problem.</p><Link href="/contact" className="text-link" data-testid="link-services-contact">Map the opportunity <ArrowRight size={15} /></Link></div></div></section><CTASection /></>;
}

const detailContent: Record<string, { eyebrow: string; title: string; description: string; icon: typeof Code2; bullets: string[]; aside: string }> = {
  "software-development": { eyebrow: "01 / Software development", title: "Build the thing your business is becoming.", description: "From a first release to a platform your teams rely on, we combine product thinking with engineering discipline to make software that earns adoption.", icon: Code2, bullets: ["Product discovery and technical strategy", "Web applications and customer portals", "Modernization of legacy platforms", "Quality engineering and delivery enablement"], aside: "Ship something useful. Then make it better." },
  "cloud-devops": { eyebrow: "02 / Cloud & DevOps", title: "Infrastructure that makes momentum easier.", description: "We design cloud environments and delivery practices that are observable, secure, and proportionate to the way your organization works.", icon: Cloud, bullets: ["Cloud strategy and migration roadmaps", "Platform engineering and infrastructure as code", "CI/CD, reliability, and observability", "Cost and performance optimization"], aside: "The best infrastructure is quietly dependable." },
  cybersecurity: { eyebrow: "03 / Cybersecurity", title: "Security that belongs in the room early.", description: "Turn security from a late-stage blocker into a clear, shared way of making better decisions about risk.", icon: ShieldCheck, bullets: ["Security posture and risk assessments", "Identity, access, and endpoint strategy", "Secure product and cloud architecture", "Incident readiness and response planning"], aside: "Practical security is a team sport." },
  "managed-it": { eyebrow: "04 / Managed IT", title: "A steadier day for your people.", description: "Responsive support and thoughtful IT operations for the work between the big transformations — delivered by people who learn your environment.", icon: Headphones, bullets: ["Help desk and end-user support", "Device, identity, and collaboration management", "Vendor and lifecycle management", "IT roadmaps and fractional leadership"], aside: "Your team should not need to think about every tool." },
  "data-ai": { eyebrow: "05 / Data & applied AI", title: "Make information useful at the moment of decision.", description: "We create the data foundations and focused AI applications that help teams see clearly, act faster, and keep humans in control.", icon: Database, bullets: ["Data platform and governance strategy", "Reporting and decision intelligence", "Workflow automation and applied AI", "Responsible AI discovery and enablement"], aside: "Intelligence is only valuable when it changes the next move." },
};

export function ServiceDetailPage({ slug }: { slug: string }) {
  const content = detailContent[slug] || detailContent["software-development"];
  const Icon = content.icon;
  return <><PageIntro eyebrow={content.eyebrow} title={content.title} text={content.description} action={{ label: "Discuss your challenge", href: "/contact" }} /><section className="section"><div className="container service-detail"><div><Icon size={42} color="hsl(var(--primary))" /><h2>{content.title}</h2><p className="lede">{content.description}</p><div className="deliverables">{content.bullets.map((bullet) => <div className="deliverable" key={bullet}><Check size={17} />{bullet}</div>)}</div></div><aside className="detail-aside"><span className="mono" style={{ color: "hsl(var(--primary))", fontSize: 10 }}>A BETTER WAY TO START</span><h3>{content.aside}</h3><p>We start with the operating reality — your goals, constraints, people, and existing systems — then make the next decision clearer.</p><Link href="/contact" className="button button-primary" data-testid="link-detail-contact">Start a conversation <ArrowUpRight size={15} /></Link></aside></div></section><section className="section" style={{ background: "hsl(var(--muted))" }}><div className="container numbered-grid"><div className="number-card"><span className="num">01 / UNDERSTAND</span><h3>Get close to the work.</h3><p>We listen for the real constraint underneath the stated request.</p></div><div className="number-card"><span className="num">02 / SHAPE</span><h3>Make the path visible.</h3><p>Options, tradeoffs, and a sequence your team can believe in.</p></div><div className="number-card"><span className="num">03 / DELIVER</span><h3>Build with conviction.</h3><p>Small feedback loops, honest status, and momentum you can feel.</p></div></div></section><CTASection title="Make the next technical decision a confident one." /></>;
}

export function IndustriesPage() {
  return <><PageIntro eyebrow="Industries" title="Context changes the right answer." text="We bring a proven technology practice, then do the work to understand the people, pressures, and promise behind your organization." /><section className="section"><div className="container"><div className="industry-grid">{industries.map((industry) => <Link href={industry.path} className="industry-card" key={industry.path} data-testid={`industry-card-${industry.code}`}><span className="mono" style={{ color: "hsl(var(--primary))" }}>{industry.code} / 04</span><div><h3>{industry.title}</h3><p>{industry.description}</p><span className="text-link">Explore context <ArrowRight size={14} /></span></div></Link>)}</div></div></section><CTASection title="Your context is the starting point." /></>;
}

const industryDetail: Record<string, { title: string; eyebrow: string; text: string; challenges: string[] }> = {
  healthcare: { title: "Technology that respects the care journey.", eyebrow: "Healthcare technology", text: "Connect people, processes, and platforms around a more reliable experience for staff and the communities they serve.", challenges: ["Modernize patient and member experiences", "Make operational data easier to trust", "Protect sensitive information by default"] },
  finance: { title: "Confidence for high-consequence work.", eyebrow: "Finance & professional services", text: "Build secure, auditable systems that help experts move faster without asking them to compromise their standards.", challenges: ["Create a clear control environment", "Modernize workflows without losing auditability", "Give teams better intelligence at the point of work"] },
  education: { title: "Better access starts behind the screen.", eyebrow: "Education & public sector", text: "Design practical digital services for institutions balancing access, accountability, and the realities of constrained resources.", challenges: ["Improve digital access and service delivery", "Connect teams across legacy systems", "Build sustainable internal capability"] },
  retail: { title: "Keep the operation moving.", eyebrow: "Retail & operations", text: "Bring the front line, the back office, and the customer experience into better alignment with systems that can keep pace.", challenges: ["Reduce friction at the point of service", "Turn operational signals into action", "Make systems resilient across locations"] },
};

export function IndustryDetailPage({ slug }: { slug: string }) {
  const content = industryDetail[slug] || industryDetail.healthcare;
  return <><PageIntro eyebrow={content.eyebrow} title={content.title} text={content.text} action={{ label: "Talk through your context", href: "/contact" }} /><section className="section"><div className="container split"><div><SectionLabel>Where we help</SectionLabel><h2>The system behind the service matters.</h2><p className="rich-copy">{content.text} Our role is to make the technical path support the human one — with fewer handoffs, clearer signals, and decisions that stand up in the real world.</p></div><div className="principles">{content.challenges.map((challenge, index) => <div className="principle" key={challenge}><span className="principle-no">0{index + 1}</span><div><h3>{challenge}</h3><p>Practical guidance, delivered with the people who will live with the result.</p></div></div>)}</div></div></section><section className="section" style={{ background: "hsl(var(--secondary))", color: "hsl(var(--secondary-foreground))" }}><div className="container split"><div><SectionLabel>Point of view</SectionLabel><h2>Technology should respect the stakes.</h2></div><p className="rich-copy" style={{ color: "hsl(210 30% 74%)" }}>In your world, “good enough” has a human cost. We bring the rigor of engineering and the humility to ask what the system needs to do for the person at the other end of it.</p></div></section><CTASection /></>;
}

export function InsightsPage() {
  return <><PageIntro eyebrow="Insights" title="Useful thinking, without the theater." text="Short, practical notes on the technology decisions growing organizations are making right now." /><section className="section"><div className="container insight-grid"><Link href="/insights/cloud-readiness" className="insight-card" data-testid="insight-page-cloud"><span className="insight-meta">01 / Cloud operations · 7 min</span><h3>Cloud readiness is a business conversation.</h3><p>Before you choose a platform, choose what “ready” needs to mean for your people.</p><span className="text-link">Read the note <ArrowRight size={14} /></span></Link><Link href="/insights/secure-by-design" className="insight-card" data-testid="insight-page-secure"><span className="insight-meta">02 / Security · 6 min</span><h3>Secure by design, not by surprise.</h3><p>Five ways to move security upstream without slowing the work down.</p><span className="text-link">Read the note <ArrowRight size={14} /></span></Link><div className="insight-card"><span className="insight-meta">03 / Operations · Coming soon</span><h3>Good systems leave room for good work.</h3><p>Our perspective on humane operations and the teams behind the tools.</p><span className="text-link" style={{ marginTop: 25 }}>Follow the thread <ArrowRight size={14} /></span></div></div></section><CTASection title="Have a question we should think about together?" /></>;
}

const articleData: Record<string, { category: string; title: string; intro: string; sections: { heading: string; body: string }[]; callout: string }> = {
  "cloud-readiness": { category: "Cloud operations / 7 min read", title: "Cloud readiness is a business conversation.", intro: "“Should we move to the cloud?” is rarely the first question worth asking. A better starting point is understanding what the organization needs to become more capable of doing.", sections: [{ heading: "Start with the work, not the platform.", body: "Cloud is an operating model, not a destination. Begin by mapping the moments where speed, resilience, visibility, or scale would change the business outcome. The platform decision gets sharper when the job is clear." }, { heading: "Readiness has more than one dimension.", body: "Look at architecture, yes. Also look at ownership, financial visibility, identity, delivery habits, and the confidence of the team who will run it. A technically ready environment can still be operationally unready." }, { heading: "Choose a next move you can learn from.", body: "The best first step is usually bounded. Pick a workload or workflow that teaches you something important without putting the business at unnecessary risk. Measure what changed, then decide what to do next." }], callout: "Cloud readiness is not about being modern. It is about being ready for the work your organization is about to do." },
  "secure-by-design": { category: "Cybersecurity / 6 min read", title: "Secure by design, not by surprise.", intro: "Security works best when it is treated as a way of making better product and operating decisions — not as a gate that appears at the end.", sections: [{ heading: "Put security in the first sketch.", body: "When security enters at the beginning, teams have more options. They can choose simpler identity models, clearer data boundaries, and safer defaults before those decisions become expensive to change." }, { heading: "Make the safe path the easy path.", body: "Policies alone do not create secure behavior. Good defaults, visible ownership, useful tooling, and short feedback loops make the right decision more natural for the people doing the work." }, { heading: "Practice for the day it matters.", body: "Incident readiness is not a document. It is a shared understanding of who does what, what gets protected first, and how communication works under pressure. Rehearse the important parts before you need them." }], callout: "The goal is not to eliminate every risk. It is to help the organization understand and manage its important risks on purpose." },
};

export function ArticlePage({ slug }: { slug: string }) {
  const article = articleData[slug] || articleData["cloud-readiness"];
  return <><section className="page-intro"><div className="container article-head animate-in"><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p className="lede">{article.intro}</p></div></section><article className="section"><div className="article-shell"><p style={{ color: "hsl(var(--foreground))", fontSize: "1.3rem", lineHeight: 1.6 }}>{article.intro}</p>{article.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}<div className="article-callout"><Sparkles size={19} style={{ marginBottom: 15 }} />{article.callout}</div><Link href="/contact" className="button button-dark" data-testid="link-article-contact">Talk to an advisor <ArrowRight size={15} /></Link></div></article></>;
}

export function CareersPage() {
  const jobs = [{ title: "Senior Software Engineer", location: "Remote / North America", type: "Full-time" }, { title: "Cloud Operations Lead", location: "Remote / North America", type: "Full-time" }, { title: "Client Technology Partner", location: "Remote / North America", type: "Full-time" }];
  return <><PageIntro eyebrow="Careers" title="Do work that has somewhere to go." text="We are building a team that can hold technical depth and human context at the same time. If that sounds like you, we would like to hear from you." action={{ label: "Send a note", href: `mailto:${contactInfo.careers}` }} /><section className="section"><div className="container split"><div><SectionLabel>Life at CodeByte</SectionLabel><h2>Good work needs good conditions.</h2></div><div className="rich-copy"><p>We work with smart people on meaningful problems, keep communication direct, and leave room for the life around the work. Our team is remote-first, senior-led, and serious about learning without taking ourselves too seriously.</p><Link href={`mailto:${contactInfo.careers}`} className="text-link" data-testid="link-careers-email">Introduce yourself <ArrowUpRight size={15} /></Link></div></div></section><section className="section" style={{ background: "hsl(var(--muted))" }}><div className="container"><div className="section-head"><div><SectionLabel>Open roles</SectionLabel><h2>Find your next useful challenge.</h2></div></div><div className="career-list">{jobs.map((job) => <div className="job-row" key={job.title}><div><h3>{job.title}</h3><p>{job.location}</p></div><span className="job-type">{job.type}</span><a href={`mailto:${contactInfo.careers}?subject=${encodeURIComponent(job.title)}`} className="button button-ghost" data-testid={`button-apply-${job.title.toLowerCase().replaceAll(" ", "-")}`}>Apply <ArrowUpRight size={14} /></a></div>)}</div></div></section><CTASection title="Do work you can point to." /></>;
}

export function ContactForm({ support = false }: { support?: boolean }) {
  const [submitted, setSubmitted] = useState(false);
  if (submitted) return <div className="success-box" data-testid="status-form-success"><Check size={24} color="hsl(var(--primary-foreground))" /><h3>Message received.</h3><p>Thanks for reaching out. This frontend demo does not send email, but your note is captured here as a clear confirmation.</p><button className="button button-dark" onClick={() => setSubmitted(false)} data-testid="button-send-another">Send another note</button></div>;
  return <form className="form-shell" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><h2>{support ? "Tell us what needs attention." : "Let’s make the next move clear."}</h2><div className="form-grid"><div className="field"><label htmlFor="name">Name</label><input id="name" required placeholder="Your name" data-testid="input-name" /></div><div className="field"><label htmlFor="email">Work email</label><input id="email" required type="email" placeholder="you@company.com" data-testid="input-email" /></div><div className="field"><label htmlFor="organization">Organization</label><input id="organization" required placeholder="Organization name" data-testid="input-organization" /></div><div className="field"><label htmlFor="topic">I’m reaching out about</label><select id="topic" defaultValue={support ? "support" : "project"} data-testid="select-topic"><option value="project">A project or opportunity</option><option value="support">Technical support</option><option value="partnership">A partnership</option><option value="careers">Careers</option></select></div><div className="field field-full"><label htmlFor="message">A little context</label><textarea id="message" required placeholder="What are you trying to make easier, safer, or possible?" data-testid="input-message" /></div></div><div className="form-foot"><span className="form-note">Frontend-only form · No data is sent anywhere.<br />We value clear, concise context.</span><button type="submit" className="button button-primary" data-testid="button-submit-contact">Submit inquiry <ArrowUpRight size={15} /></button></div></form>;
}

export function ContactPage({ support = false, sales = false }: { support?: boolean; sales?: boolean }) {
  const eyebrow = support ? "Support desk" : sales ? "Sales inquiry" : "Contact";
  const title = support ? "Let’s get the work moving again." : sales ? "Find the right place to start." : "Start with a useful conversation.";
  const intro = support ? "For current clients and support requests, share the shape of the issue and our team will know where to start." : sales ? "Tell us what you are planning, what is getting in the way, and what a better outcome would look like." : "Tell us what you are trying to make easier, safer, or possible. We will bring the right people to the first conversation.";
  const email = support ? contactInfo.support : sales ? contactInfo.sales : contactInfo.email;
  return <><PageIntro eyebrow={eyebrow} title={title} text={intro} /><section className="section"><div className="container contact-layout"><aside className="contact-panel"><span className="eyebrow">On the other end</span><h2>Real people.<br />Clear answers.</h2><p>Use the form for a new project, a technical question, or simply to compare notes. No hard sell. No maze.</p><div className="contact-detail"><Mail size={18} /><div><small>Email</small><a href={`mailto:${email}`} data-testid="contact-email">{email}</a></div></div><div className="contact-detail"><Phone size={18} /><div><small>Phone</small><a href={`tel:${contactInfo.phone}`} data-testid="contact-phone">{contactInfo.phone}</a></div></div><div className="contact-detail"><Clock3 size={18} /><div><small>Response window</small><span>Usually within one business day</span></div></div><div className="contact-detail"><MapPin size={18} /><div><small>Bengaluru office</small><span>{contactInfo.offices[0]}</span></div></div><div className="contact-detail"><MapPin size={18} /><div><small>Pune office</small><span>{contactInfo.offices[1]}</span></div></div></aside><ContactForm support={support} /></div></section></>;
}

export function NotFoundPage() {
  return <><PageIntro eyebrow="404 / Not found" title="This page took a wrong turn." text="The address may have changed, or the link may have been a little too ambitious." action={{ label: "Return home", href: "/" }} /><section className="section"><div className="container" style={{ textAlign: "center" }}><Terminal size={48} color="hsl(var(--primary))" /><p className="lede" style={{ margin: "20px auto" }}>Try the main navigation, or start a conversation if you were looking for something specific.</p><Link href="/contact" className="text-link" data-testid="link-not-found-contact">Contact CodeByte <ArrowRight size={15} /></Link></div></section></>;
}